import type { Metadata } from 'next'
import localFont from 'next/font/local'

import { cn } from '~/lib/utils'

import './globals.css'

const base = localFont({ src: './fonts/ComicNeue.ttf' })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={cn('antialiased dark', base.className)}>{children}</body>
    </html>
  )
}
